[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at QuickDB.table (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:209:16)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:47:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at QuickDB.table (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:209:16)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:44:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at QuickDB.table (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:209:16)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:49:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at QuickDB.table (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:209:16)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:45:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at QuickDB.table (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:209:16)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:46:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at QuickDB.table (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:209:16)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:48:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:00] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.prepare (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:36:25)
    at new QuickDB (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:35:37)
    at Database.initDatabase (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\structures\database\Database.js:41:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[02/04/2025, 19:33:01] [ERROR] Error: Access denied for user 'u92364_lkQM8rvN5z'@'200.118.145.60' (using password: YES)
    at PromisePool.query (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\mysql2\lib\promise\pool.js:36:22)
    at MySQLDriver.getRowByKey (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\drivers\MySQLDriver.js:48:40)
    at QuickDB.get (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\quick.db\out\index.js:92:44)
    at Ready.run (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\events\client\ready.js:30:58)
    at BotClient.<anonymous> (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\handlers\events.js:14:41)
    at BotClient.emit (node:events:518:28)
    at WebSocketManager.triggerClientReady (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:381:17)
    at WebSocketManager.checkShardsReady (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:364:10)
    at WebSocketShard.<anonymous> (C:\Users\DarkCheddar\Documents\QuickLand\QuickBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:194:16)
    at WebSocketShard.emit (node:events:518:28)
[02/04/2025, 20:15:14] [ERROR] Bot haven't been invited with applications.commands scope. Please ReInvite Bot with Required Scope(s).
